import hashlib
import json
from io import StringIO
from types import SimpleNamespace

from forge_workers.mujoco_parity import (
    PINNED_MUJOCO_VERSION,
    MuJoCoParityRequest,
    MuJoCoParityScene,
    _validate_runtime_model,
    baseline_artifact,
    main,
    request_from_payload,
    run_baseline,
)


def request_payload(**overrides):
    payload = {
        "artifactKind": "simParityMuJoCoRequest",
        "schemaVersion": "1.0.0",
        "task": "sim.parity",
        "sourceRevision": "a" * 40,
        "requestSha256": "b" * 64,
        "mujocoVersion": PINNED_MUJOCO_VERSION,
        "gravity": 9.80665,
        "dropHeightM": 1.0,
        "pendulumLengthM": 0.4,
        "hoverTrim": 0.42,
        "gaitComM": 0.004,
        "driverDtS": 1.0 / 240.0,
        "substeps": 4,
        "scenes": {
            name: {
                "bodyName": body,
                "mjcf": (
                    f'<!-- generated by forge-sim from contract parity-{name} (schema 2.2.0) -->\n'
                    f'<mujoco model="parity-{name}"><compiler angle="radian"/>'
                    f'<worldbody><body name="{body}"/></worldbody></mujoco>'
                ),
            }
            for name, body in {
                "drop": "drop",
                "pendulum": "bob",
                "hover": "hover",
                "gait": "gait",
            }.items()
        },
    }
    payload.update(overrides)
    if "requestSha256" not in overrides:
        request_body = {
            key: value
            for key, value in payload.items()
            if key not in ("sourceRevision", "requestSha256")
        }
        payload["requestSha256"] = hashlib.sha256(
            json.dumps(
                request_body,
                separators=(",", ":"),
                ensure_ascii=False,
            ).encode("utf-8")
        ).hexdigest()
    return payload


def test_request_parsing_defaults_and_rejects_wrong_task():
    request = request_from_payload(request_payload(pendulumLengthM=0.5))
    assert request.gravity == 9.80665
    assert request.drop_height_m == 1.0
    assert request.pendulum_length_m == 0.5
    assert request.substeps == 4
    assert request.drop == MuJoCoParityScene(
        body_name="drop",
        mjcf=(
            '<!-- generated by forge-sim from contract parity-drop (schema 2.2.0) -->\n'
            '<mujoco model="parity-drop"><compiler angle="radian"/>'
            '<worldbody><body name="drop"/></worldbody></mujoco>'
        ),
    )

    try:
        request_from_payload(request_payload(task="train.policy"))
    except ValueError as exc:
        assert "unsupported task" in str(exc)
    else:
        raise AssertionError("wrong task should be rejected")


def test_request_rejects_unpinned_runtime_and_missing_contract_scene():
    try:
        request_from_payload(request_payload(mujocoVersion="3.10.0"))
    except ValueError as exc:
        assert "reviewed pin" in str(exc)
    else:
        raise AssertionError("unpinned runtime should be rejected")

    payload = request_payload()
    del payload["scenes"]["gait"]
    try:
        request_from_payload(payload)
    except ValueError as exc:
        assert "scenes must contain exactly" in str(exc)
    else:
        raise AssertionError("missing canonical scene should be rejected")

    payload = request_payload()
    payload["scenes"]["drop"]["mjcf"] = payload["scenes"]["drop"]["mjcf"].replace(
        "<worldbody>", '<asset><mesh file="/etc/passwd"/></asset><worldbody>'
    )
    try:
        request_from_payload(payload)
    except ValueError as exc:
        assert "contract-derived MJCF" in str(exc)
    else:
        raise AssertionError("external-file MJCF should be rejected")

    payload = request_payload()
    payload["gravity"] = 3.711
    try:
        request_from_payload(payload)
    except ValueError as exc:
        assert "canonical request payload" in str(exc)
    else:
        raise AssertionError("request hash drift should be rejected")


def test_baseline_artifact_matches_validator_decode_shape():
    request = MuJoCoParityRequest(hover_trim=0.43, gait_com_m=0.006)
    artifact = baseline_artifact(
        request,
        drop_time_s=0.451,
        pendulum_period_s=1.27,
        hover_trim=0.431,
        gait_com_m=0.0061,
        provider="unit",
    )

    assert artifact["artifactKind"] == "simParityMuJoCoBaseline"
    assert artifact["schemaVersion"] == "1.0.0"
    assert artifact["sourceRevision"] == "0" * 40
    assert artifact["requestSha256"] == "0" * 64
    assert artifact["provider"] == "unit"
    assert artifact["baseline"]["dropHeightM"] == 1.0
    assert artifact["baseline"]["mujocoDropTimeS"] == 0.451
    assert artifact["baseline"]["mujocoHoverTrim"] == 0.431
    assert artifact["baseline"]["mujocoGaitComM"] == 0.0061


def test_command_fails_closed_when_mujoco_is_not_installed(monkeypatch):
    def _missing(_payload):
        raise RuntimeError("MuJoCo Python package is not installed")

    monkeypatch.setattr("forge_workers.mujoco_parity.run_baseline", _missing)
    stdout = StringIO()
    stderr = StringIO()
    code = main(
        stdin=StringIO(json.dumps(request_payload())),
        stdout=stdout,
        stderr=stderr,
    )

    assert code == 2
    assert stdout.getvalue() == ""
    assert "MuJoCo Python package is not installed" in stderr.getvalue()


def test_runner_rejects_engine_and_compiled_runtime_drift_before_execution():
    class WrongVersion:
        __version__ = "3.10.0"

    try:
        run_baseline(request_payload(), WrongVersion())
    except RuntimeError as exc:
        assert "does not match request pin" in str(exc)
    else:
        raise AssertionError("runtime version drift should fail closed")

    request = request_from_payload(request_payload())
    model = SimpleNamespace(
        opt=SimpleNamespace(
            timestep=request.timestep_s,
            gravity=(0.0, 0.0, -request.gravity),
        )
    )
    _validate_runtime_model(model, request, "test")
    model.opt.timestep *= 2.0
    try:
        _validate_runtime_model(model, request, "test")
    except RuntimeError as exc:
        assert "timestep" in str(exc)
    else:
        raise AssertionError("compiled timestep drift should fail closed")
