// GENERATED by scripts/codegen-contract.mjs from schema/forge-modelspec.schema.json
// (schemars emission from crates/forge-contract — the schema's single source, D16).
// Do not edit; run `pnpm codegen:contract` after changing the Rust types.

export type Archetype = "biped" | "multirotor" | "rover" | "arm" | "quadruped" | "fixedwing";
export type ProvenanceKind = "human" | "parametric-generator" | "llm-generation";
/**
 * The primitive vocabulary (tagged union). Dimension fields are meters.
 * Exact parameterizations beyond Appendix A are *(proposed)* until reconciled
 * against the prototype (PRE-002).
 */
export type Geom =
  | {
      d: number;
      h: number;
      kind: "box";
      w: number;
    }
  | {
      ch: number;
      d: number;
      h: number;
      kind: "cbox";
      w: number;
    }
  | {
      d0: number;
      d1: number;
      h: number;
      kind: "taper";
      w0: number;
      w1: number;
    }
  | {
      h: number;
      kind: "cyl";
      n?: number | null;
      r0: number;
      r1?: number | null;
    }
  | {
      kind: "lathe";
      n?: number | null;
      profile: [number, number][];
    }
  | {
      e: number;
      h: number;
      kind: "squircle";
      n?: number | null;
      rx: number;
      rz: number;
    }
  | {
      kind: "loft";
      profile: LoftProfile;
      stations: LoftStation[];
    }
  | {
      kind: "mesh";
      ref: string;
    };
/**
 * Loft cross-section profile.
 */
export type LoftProfile =
  | {
      e: number;
      kind: "sq";
      n: number;
    }
  | {
      kind: "circle";
      n: number;
    };
export type MaterialClass = "gloss" | "metal" | "satin" | "matte" | "rubber";
export type EstimatorKind = "complementary" | "ekf";
export type JointKind = "fixed" | "revolute" | "spherical";

export interface ModelSpec {
  chains?: Chain[];
  driver: Driver;
  env?: EnvBlock;
  /**
   * componentRef@range → exact immutable revision (D5).
   */
  lockfile?: {
    [k: string]: string;
  };
  meta: Meta;
  parts: Part[];
  ports?: Port[];
  sim?: SimBlock;
  skeleton: Node[];
  slots?: Slot[];
}
/**
 * Staged disassembly: one row per kinematic-chain node, reconciled to the
 * prototype's chains table `[node, dir, dist, t0, t1]` (PRE-002).
 */
export interface Chain {
  /**
   * Node-local explode direction.
   *
   * @minItems 3
   * @maxItems 3
   */
  dir?: [number, number, number] | null;
  id: string;
  /**
   * Travel distance, meters.
   */
  mag?: number | null;
  nodes: string[];
  stage: number;
  /**
   * Window within the global explode phase.
   */
  t0?: number | null;
  t1?: number | null;
}
export interface Driver {
  archetype: Archetype;
  /**
   * Archetype-specific parameter block, validated by the driver library's
   * param schema at admission.
   */
  params?: {
    [k: string]: unknown;
  };
}
export interface EnvBlock {
  /**
   * kg/m³
   */
  airDensity?: number;
  /**
   * m/s²
   */
  gravity?: number;
  wind?: Wind;
}
export interface Wind {
  gust?: number;
  mean?: number;
}
export interface Meta {
  archetype: Archetype;
  id: string;
  license: string;
  name: string;
  provenance: Provenance;
  /**
   * Semver of this model document.
   */
  version: string;
}
export interface Provenance {
  kind: ProvenanceKind;
  modelVersion?: string | null;
  promptHash?: string | null;
  seed?: number | null;
}
export interface Part {
  collision?: "auto" | "hull" | "primitive" | "none";
  /**
   * Hex color, e.g. "#23262c".
   */
  color: string;
  /**
   * Component tag for pick resolution (BEH-004).
   */
  comp?: string | null;
  explode?: Explode | null;
  geom: Geom;
  mass?: MassSpec | null;
  material: MaterialClass;
  /**
   * Skeleton node this part attaches to.
   */
  node: string;
  pose?: PartPose | null;
  /**
   * Polygon-offset hint for true coplanar decals only (plan §7.2).
   */
  renderBias?: number | null;
}
export interface Explode {
  /**
   * Direction (node-local) the part travels during staged explode.
   *
   * @minItems 3
   * @maxItems 3
   */
  dir: [number, number, number];
  /**
   * Leader-flagged subassembly label (counts toward CTR-004).
   */
  leader?: string | null;
  /**
   * Travel magnitude in meters.
   */
  mag: number;
  /**
   * Window within the global explode phase [0,1].
   */
  t0: number;
  t1: number;
}
export interface LoftStation {
  /**
   * Corner roundness 0..1 (0 = boxy, 1 = elliptical). Parameterization is
   * *(proposed)* pending prototype reconciliation (PRE-002).
   */
  r?: number | null;
  /**
   * Half-extent scale along X (meters).
   */
  sx: number;
  /**
   * Half-extent scale along Z (meters).
   */
  sz: number;
  /**
   * Height of this station along local Y (meters).
   */
  y: number;
}
/**
 * Mass is either stated directly (grams, schema surface) or derived from the
 * part's volume × a density override; absent → density from the material class.
 */
export interface MassSpec {
  densityKgm3?: number | null;
  valueG?: number | null;
}
/**
 * Part-local pose applied before node placement (prototype `P(node, mesh,
 * {p, r, s})` — the executable spec). Rotation composes T·Ry·Rx·Rz·S.
 */
export interface PartPose {
  /**
   * @minItems 3
   * @maxItems 3
   */
  p?: [number, number, number];
  /**
   * @minItems 3
   * @maxItems 3
   */
  r?: [number, number, number];
  /**
   * @minItems 3
   * @maxItems 3
   */
  s?: [number, number, number];
}
export interface Port {
  /**
   * Explicitly capped ports count as resolved (CTR-002).
   */
  capped?: boolean;
  /**
   * [[x,y,z],[rx,ry,rz]] node-local frame.
   *
   * @minItems 2
   * @maxItems 2
   */
  frame: [[number, number, number], [number, number, number]];
  id: string;
  node: string;
  /**
   * Connector taxonomy type, e.g. "XT60", "stack-30.5x30.5-M3", "UART".
   */
  type: string;
}
export interface SimBlock {
  /**
   * Aggregate mass override in grams; when present, GEO-006 checks closure.
   */
  aggregateMassG?: number | null;
  battery?: Battery | null;
  colliders?: ColliderPolicy;
  estimator?: Estimator | null;
  motors?: MotorSpec[];
  props?: PropSpec[];
}
export interface Battery {
  cRating?: number | null;
  capacity_mAh: number;
  cells: number;
  /**
   * Plan Appendix A spells this snake_case; the appendix is authoritative.
   */
  r_int_mohm: number;
}
export interface ColliderPolicy {
  budget?: ColliderBudget;
  policy?: string;
}
export interface ColliderBudget {
  perModel?: number;
  perNode?: number;
}
export interface Estimator {
  accelNoise: number;
  bias: number;
  gyroNoise: number;
  kind: EstimatorKind;
  /**
   * Plan Appendix A spells this snake_case; the appendix is authoritative.
   */
  latency_ms: number;
}
export interface MotorSpec {
  /**
   * Spin direction: +1 CCW, -1 CW (mixer input). Defaults alternate by index.
   */
  dir?: number | null;
  /**
   * Inline motor constants (synthetic/generated parts) …
   */
  kv?: number | null;
  maxCurrentA?: number | null;
  /**
   * Mount node (e.g. "m0").
   */
  mount: string;
  r_int_mohm?: number | null;
  /**
   * … or a catalog reference (resolved through the lockfile, D5).
   */
  ref?: string | null;
}
export interface PropSpec {
  blades: number;
  /**
   * Optional published thrust table reference (XC-06).
   */
  ctTable?: string | null;
  diameterIn: number;
  pitchIn: number;
}
export interface Node {
  joint?: Joint | null;
  /**
   * Per-axis [min,max] joint limits in radians: [[minX,maxX],[minY,maxY],[minZ,maxZ]].
   *
   * @minItems 3
   * @maxItems 3
   */
  limits?: [[number, number], [number, number], [number, number]] | null;
  name: string;
  /**
   * `None` for the root node.
   */
  parent?: string | null;
  /**
   * Meters, parent-local.
   *
   * @minItems 3
   * @maxItems 3
   */
  pos: [number, number, number];
  /**
   * Radians, XYZ euler, parent-local.
   *
   * @minItems 3
   * @maxItems 3
   */
  rot?: [number, number, number];
}
export interface Joint {
  /**
   * @minItems 3
   * @maxItems 3
   */
  axis?: [number, number, number] | null;
  maxTorqueNm?: number | null;
  maxVelRad?: number | null;
  type: JointKind;
}
export interface Slot {
  id: string;
  joint?: Joint | null;
  label: string;
  mountNodes: string[];
  variants: Variant[];
}
export interface Variant {
  /**
   * Semver-ranged reference into the catalog, e.g. "cmp_pack_4s1500@^2" (D5).
   */
  componentRef?: string | null;
  desc?: string | null;
  id: string;
  name?: string | null;
  /**
   * Inline parts (exactly one of `parts` / `componentRef` must be present —
   * enforced by CTR-003 semantics, not by shape).
   */
  parts?: Part[] | null;
  /**
   * Port declarations contributed by this variant (e.g. {"elec": "XT60"}).
   */
  ports?: {
    [k: string]: string;
  };
}
